// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeC2bQy3P5QIUMxwMjRp0GOwUISDjaz1M',
    appId: '1:337343333139:web:7e50f1194df6a8efeb50e6',
    messagingSenderId: '337343333139',
    projectId: 'csretrieval',
    authDomain: 'csretrieval.firebaseapp.com',
    storageBucket: 'csretrieval.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9SSHxRPNRPQaDRpRUmZwIYNG0z93utzk',
    appId: '1:337343333139:android:8eefc98f472b6d4deb50e6',
    messagingSenderId: '337343333139',
    projectId: 'csretrieval',
    storageBucket: 'csretrieval.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe2fL8LK42C_sDqHVQ4v8NQnIyVfMre9A',
    appId: '1:337343333139:ios:684e72011cd405cbeb50e6',
    messagingSenderId: '337343333139',
    projectId: 'csretrieval',
    storageBucket: 'csretrieval.appspot.com',
    iosClientId: '337343333139-tdn908s0he1p9fova6bl8li6d6famig7.apps.googleusercontent.com',
    iosBundleId: 'app.retrieval.retrievalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe2fL8LK42C_sDqHVQ4v8NQnIyVfMre9A',
    appId: '1:337343333139:ios:684e72011cd405cbeb50e6',
    messagingSenderId: '337343333139',
    projectId: 'csretrieval',
    storageBucket: 'csretrieval.appspot.com',
    iosClientId: '337343333139-tdn908s0he1p9fova6bl8li6d6famig7.apps.googleusercontent.com',
    iosBundleId: 'app.retrieval.retrievalapp',
  );
}
